# Project Identification
sonar.projectKey=GuardiansOfTheGit-Sonar-Qube-Test
sonar.projectName=GuardiansOfTheGit-Sonar-Qube-Test
sonar.projectVersion=1.0

# Source Directory
sonar.sources=src

# Exclusions
sonar.exclusions=src/**/*
sonar.inclusions=src/*

# Server URL and Login
sonar.host.url=http://localhost:9000
sonar.login=sqp_db7754a3c6e2774bd100e458891aa94f45321cd6
